import type { Guide, Tour, Category } from '../types/guide';

export const CATEGORIES: Category[] = [
  { id: 'cultural', name: 'Cultural', icon: '🏛️', color: '#6366F1' },
  { id: 'gastronomy', name: 'Gastronomía', icon: '🍷', color: '#EC4899' },
  { id: 'adventure', name: 'Aventura', icon: '🏔️', color: '#10B981' },
  { id: 'history', name: 'Historia', icon: '📜', color: '#F59E0B' },
  { id: 'nature', name: 'Naturaleza', icon: '🌿', color: '#22C55E' },
  { id: 'nightlife', name: 'Vida Nocturna', icon: '🌙', color: '#8B5CF6' },
  { id: 'photography', name: 'Fotografía', icon: '📸', color: '#3B82F6' },
  { id: 'art', name: 'Arte', icon: '🎨', color: '#F43F5E' },
];

export const MOCK_GUIDES: Guide[] = [
  {
    id: '1',
    name: 'María García',
    avatar: undefined,
    rating: 4.9,
    reviewCount: 234,
    location: 'Madrid, España',
    languages: ['Español', 'Inglés', 'Francés'],
    specialties: ['Historia', 'Arte', 'Arquitectura'],
    bio: 'Guía oficial con más de 10 años de experiencia. Especializada en el Madrid de los Austrias y el Museo del Prado.',
    pricePerHour: 45,
    currency: 'EUR',
    verified: true,
    featured: true,
    available: true,
  },
  {
    id: '2',
    name: 'Carlos Rodríguez',
    avatar: undefined,
    rating: 4.8,
    reviewCount: 189,
    location: 'Barcelona, España',
    languages: ['Español', 'Inglés', 'Catalán'],
    specialties: ['Gastronomía', 'Cultura Local', 'Vida Nocturna'],
    bio: 'Barcelonés de nacimiento, apasionado por la gastronomía local y los secretos de la ciudad.',
    pricePerHour: 50,
    currency: 'EUR',
    verified: true,
    featured: true,
    available: true,
  },
  {
    id: '3',
    name: 'Ana Martínez',
    avatar: undefined,
    rating: 4.7,
    reviewCount: 156,
    location: 'Sevilla, España',
    languages: ['Español', 'Inglés'],
    specialties: ['Flamenco', 'Historia', 'Tradiciones'],
    bio: 'Enamorada de Sevilla y sus tradiciones. Te mostraré la esencia del sur de España.',
    pricePerHour: 40,
    currency: 'EUR',
    verified: true,
    featured: false,
    available: true,
  },
  {
    id: '4',
    name: 'Pedro Sánchez',
    avatar: undefined,
    rating: 4.9,
    reviewCount: 312,
    location: 'Granada, España',
    languages: ['Español', 'Inglés', 'Alemán'],
    specialties: ['Alhambra', 'Historia Árabe', 'Naturaleza'],
    bio: 'Historiador especializado en la época nazarí. La Alhambra no tiene secretos para mí.',
    pricePerHour: 55,
    currency: 'EUR',
    verified: true,
    featured: true,
    available: false,
  },
  {
    id: '5',
    name: 'Laura Fernández',
    avatar: undefined,
    rating: 4.6,
    reviewCount: 98,
    location: 'Valencia, España',
    languages: ['Español', 'Inglés', 'Italiano'],
    specialties: ['Gastronomía', 'Modernismo', 'Playas'],
    bio: 'Chef y guía turística. Combino la historia de Valencia con su increíble gastronomía.',
    pricePerHour: 48,
    currency: 'EUR',
    verified: false,
    featured: false,
    available: true,
  },
];

export const MOCK_TOURS: Tour[] = [
  {
    id: '1',
    title: 'Madrid de los Austrias',
    description: 'Descubre el corazón histórico de Madrid, desde la Plaza Mayor hasta el Palacio Real.',
    image: undefined,
    guideId: '1',
    guideName: 'María García',
    guideAvatar: undefined,
    guideRating: 4.9,
    location: 'Madrid',
    duration: '3 horas',
    price: 35,
    currency: 'EUR',
    maxParticipants: 10,
    categories: ['cultural', 'history'],
    includes: ['Guía experto', 'Entrada a monumentos', 'Mapa histórico'],
    rating: 4.9,
    reviewCount: 128,
    featured: true,
  },
  {
    id: '2',
    title: 'Tapas y Vinos en Barcelona',
    description: 'Ruta gastronómica por los mejores bares de tapas del Born y el Gótico.',
    image: undefined,
    guideId: '2',
    guideName: 'Carlos Rodríguez',
    guideAvatar: undefined,
    guideRating: 4.8,
    location: 'Barcelona',
    duration: '4 horas',
    price: 65,
    currency: 'EUR',
    maxParticipants: 8,
    categories: ['gastronomy'],
    includes: ['5 tapas', '4 vinos', 'Guía gastronómico'],
    rating: 4.8,
    reviewCount: 95,
    featured: true,
  },
  {
    id: '3',
    title: 'Sevilla Flamenca',
    description: 'Sumérgete en el mundo del flamenco, su historia y sus lugares emblemáticos.',
    image: undefined,
    guideId: '3',
    guideName: 'Ana Martínez',
    guideAvatar: undefined,
    guideRating: 4.7,
    location: 'Sevilla',
    duration: '2.5 horas',
    price: 30,
    currency: 'EUR',
    maxParticipants: 12,
    categories: ['cultural', 'art'],
    includes: ['Guía experto', 'Entrada a tablao', 'Bebida incluida'],
    rating: 4.7,
    reviewCount: 76,
    featured: false,
  },
  {
    id: '4',
    title: 'Alhambra al Atardecer',
    description: 'Visita guiada a la Alhambra durante las horas doradas del atardecer.',
    image: undefined,
    guideId: '4',
    guideName: 'Pedro Sánchez',
    guideAvatar: undefined,
    guideRating: 4.9,
    location: 'Granada',
    duration: '3 horas',
    price: 75,
    currency: 'EUR',
    maxParticipants: 6,
    categories: ['cultural', 'history', 'photography'],
    includes: ['Entrada preferente', 'Guía historiador', 'Auriculares'],
    rating: 4.9,
    reviewCount: 203,
    featured: true,
  },
  {
    id: '5',
    title: 'Valencia: Paella y Mercado',
    description: 'Visita al Mercado Central y clase de cocina de paella tradicional.',
    image: undefined,
    guideId: '5',
    guideName: 'Laura Fernández',
    guideAvatar: undefined,
    guideRating: 4.6,
    location: 'Valencia',
    duration: '5 horas',
    price: 85,
    currency: 'EUR',
    maxParticipants: 6,
    categories: ['gastronomy'],
    includes: ['Ingredientes', 'Clase de cocina', 'Almuerzo completo', 'Receta'],
    rating: 4.6,
    reviewCount: 54,
    featured: false,
  },
  {
    id: '6',
    title: 'Museo del Prado: Obras Maestras',
    description: 'Recorrido por las obras más importantes del Prado con historiadora del arte.',
    image: undefined,
    guideId: '1',
    guideName: 'María García',
    guideAvatar: undefined,
    guideRating: 4.9,
    location: 'Madrid',
    duration: '2.5 horas',
    price: 45,
    currency: 'EUR',
    maxParticipants: 8,
    categories: ['cultural', 'art'],
    includes: ['Entrada sin colas', 'Guía especializado', 'Auriculares'],
    rating: 4.9,
    reviewCount: 167,
    featured: true,
  },
];

export const LANGUAGES = [
  'Español',
  'Inglés',
  'Francés',
  'Alemán',
  'Italiano',
  'Portugués',
  'Catalán',
  'Chino',
  'Japonés',
];

export const LOCATIONS = [
  'Madrid',
  'Barcelona',
  'Sevilla',
  'Granada',
  'Valencia',
  'Bilbao',
  'San Sebastián',
  'Málaga',
];

