import type { Guide, Tour, Category } from '../types/guide';

// Placeholder images - These would come from S3 in production
const AVATAR_IMAGES = {
  carolina: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
  matias: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
  francisca: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
  sebastian: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
  valentina: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face',
  rodrigo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face',
};

const TOUR_IMAGES = {
  santiago: 'https://images.unsplash.com/photo-1558862107-d49ef2a04d72?w=600&h=400&fit=crop',
  valparaiso: 'https://images.unsplash.com/photo-1594489428504-5c0c480a15fd?w=600&h=400&fit=crop',
  atacama: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=600&h=400&fit=crop',
  torres: 'https://images.unsplash.com/photo-1531804055935-76f44d7c3621?w=600&h=400&fit=crop',
  vina: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop',
  pucon: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=400&fit=crop',
  chiloé: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
  elqui: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=600&h=400&fit=crop',
  cajon: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&h=400&fit=crop',
  wine: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=600&h=400&fit=crop',
};

// Location coordinates for map markers - Chilean cities
export const LOCATION_COORDINATES: { [key: string]: { latitude: number; longitude: number } } = {
  'Santiago': { latitude: -33.4489, longitude: -70.6693 },
  'Santiago, Chile': { latitude: -33.4489, longitude: -70.6693 },
  'Valparaíso': { latitude: -33.0472, longitude: -71.6127 },
  'Valparaíso, Chile': { latitude: -33.0472, longitude: -71.6127 },
  'Viña del Mar': { latitude: -33.0153, longitude: -71.5500 },
  'Viña del Mar, Chile': { latitude: -33.0153, longitude: -71.5500 },
  'San Pedro de Atacama': { latitude: -22.9087, longitude: -68.1997 },
  'San Pedro de Atacama, Chile': { latitude: -22.9087, longitude: -68.1997 },
  'Puerto Natales': { latitude: -51.7311, longitude: -72.4977 },
  'Puerto Natales, Chile': { latitude: -51.7311, longitude: -72.4977 },
  'Pucón': { latitude: -39.2823, longitude: -71.9545 },
  'Pucón, Chile': { latitude: -39.2823, longitude: -71.9545 },
  'Puerto Varas': { latitude: -41.3167, longitude: -72.9833 },
  'Puerto Varas, Chile': { latitude: -41.3167, longitude: -72.9833 },
  'La Serena': { latitude: -29.9027, longitude: -71.2519 },
  'La Serena, Chile': { latitude: -29.9027, longitude: -71.2519 },
  'Concepción': { latitude: -36.8201, longitude: -73.0444 },
  'Concepción, Chile': { latitude: -36.8201, longitude: -73.0444 },
  'Castro': { latitude: -42.4800, longitude: -73.7650 },
  'Castro, Chile': { latitude: -42.4800, longitude: -73.7650 },
  'Chiloé': { latitude: -42.4800, longitude: -73.7650 },
  'Chiloé, Chile': { latitude: -42.4800, longitude: -73.7650 },
  'Valle del Elqui': { latitude: -30.1333, longitude: -70.5000 },
  'Valle del Elqui, Chile': { latitude: -30.1333, longitude: -70.5000 },
  'Cajón del Maipo': { latitude: -33.6000, longitude: -70.1000 },
  'Cajón del Maipo, Chile': { latitude: -33.6000, longitude: -70.1000 },
};

// Default map region (Chile center)
export const DEFAULT_MAP_REGION = {
  latitude: -33.5,
  longitude: -70.6,
  latitudeDelta: 12,
  longitudeDelta: 12,
};

export const CATEGORIES: Category[] = [
  { id: 'adventure', name: 'Aventura', icon: '🏔️', color: '#10B981' },
  { id: 'nature', name: 'Naturaleza', icon: '🌿', color: '#22C55E' },
  { id: 'gastronomy', name: 'Gastronomía', icon: '🍷', color: '#EC4899' },
  { id: 'cultural', name: 'Cultural', icon: '🏛️', color: '#6366F1' },
  { id: 'trekking', name: 'Trekking', icon: '🥾', color: '#F59E0B' },
  { id: 'astronomy', name: 'Astronomía', icon: '🌌', color: '#8B5CF6' },
  { id: 'photography', name: 'Fotografía', icon: '📸', color: '#3B82F6' },
  { id: 'wine', name: 'Vinos', icon: '🍇', color: '#F43F5E' },
];

export const MOCK_GUIDES: Guide[] = [
  {
    id: '1',
    name: 'Carolina Muñoz',
    avatar: AVATAR_IMAGES.carolina,
    rating: 4.9,
    reviewCount: 234,
    location: 'Santiago, Chile',
    languages: ['Español', 'Inglés', 'Francés'],
    specialties: ['Historia', 'Arte', 'City Tours'],
    bio: 'Guía certificada con más de 10 años de experiencia. Especializada en el Santiago histórico y los mejores rincones de la capital.',
    pricePerHour: 35000,
    currency: 'CLP',
    verified: true,
    featured: true,
    available: true,
  },
  {
    id: '2',
    name: 'Matías Soto',
    avatar: AVATAR_IMAGES.matias,
    rating: 4.8,
    reviewCount: 189,
    location: 'San Pedro de Atacama, Chile',
    languages: ['Español', 'Inglés', 'Portugués'],
    specialties: ['Astronomía', 'Desierto', 'Fotografía'],
    bio: 'Atacameño de corazón. Experto en el desierto más árido del mundo y sus cielos estrellados únicos.',
    pricePerHour: 45000,
    currency: 'CLP',
    verified: true,
    featured: true,
    available: true,
  },
  {
    id: '3',
    name: 'Francisca Vargas',
    avatar: AVATAR_IMAGES.francisca,
    rating: 4.7,
    reviewCount: 156,
    location: 'Valparaíso, Chile',
    languages: ['Español', 'Inglés'],
    specialties: ['Arte Callejero', 'Historia', 'Gastronomía'],
    bio: 'Enamorada de los cerros de Valparaíso y su arte urbano. Te mostraré la esencia del puerto bohemio.',
    pricePerHour: 30000,
    currency: 'CLP',
    verified: true,
    featured: false,
    available: true,
  },
  {
    id: '4',
    name: 'Sebastián Lagos',
    avatar: AVATAR_IMAGES.sebastian,
    rating: 4.9,
    reviewCount: 312,
    location: 'Puerto Natales, Chile',
    languages: ['Español', 'Inglés', 'Alemán'],
    specialties: ['Torres del Paine', 'Trekking', 'Naturaleza'],
    bio: 'Guía de montaña certificado. Torres del Paine es mi segunda casa. Expediciones seguras y memorables.',
    pricePerHour: 55000,
    currency: 'CLP',
    verified: true,
    featured: true,
    available: true,
  },
  {
    id: '5',
    name: 'Valentina Reyes',
    avatar: AVATAR_IMAGES.valentina,
    rating: 4.6,
    reviewCount: 98,
    location: 'Pucón, Chile',
    languages: ['Español', 'Inglés', 'Italiano'],
    specialties: ['Aventura', 'Volcanes', 'Termas'],
    bio: 'Amante de los deportes de aventura. Te llevaré al volcán Villarrica y las mejores termas del sur.',
    pricePerHour: 40000,
    currency: 'CLP',
    verified: true,
    featured: false,
    available: true,
  },
  {
    id: '6',
    name: 'Rodrigo Fuentes',
    avatar: AVATAR_IMAGES.rodrigo,
    rating: 4.8,
    reviewCount: 145,
    location: 'Valle del Elqui, Chile',
    languages: ['Español', 'Inglés'],
    specialties: ['Astronomía', 'Vinos', 'Pisco'],
    bio: 'Sommelier y astro-guía. Combino las estrellas del Valle del Elqui con los mejores piscos y vinos de la zona.',
    pricePerHour: 38000,
    currency: 'CLP',
    verified: true,
    featured: true,
    available: true,
  },
];

export const MOCK_TOURS: Tour[] = [
  {
    id: '1',
    title: 'Santiago Histórico y Cultural',
    description:
      'Descubre el corazón de Santiago, desde la Plaza de Armas hasta el Barrio Lastarria y el Cerro Santa Lucía.',
    image: TOUR_IMAGES.santiago,
    guideId: '1',
    guideName: 'Carolina Muñoz',
    guideAvatar: AVATAR_IMAGES.carolina,
    guideRating: 4.9,
    location: 'Santiago',
    duration: '4 horas',
    price: 35000,
    currency: 'CLP',
    maxParticipants: 10,
    categories: ['cultural', 'photography'],
    includes: ['Guía experto', 'Transporte', 'Degustación de café'],
    rating: 4.9,
    reviewCount: 128,
    featured: true,
  },
  {
    id: '2',
    title: 'Tour Astronómico en Atacama',
    description: 'Observación de estrellas en el desierto más árido del mundo con telescopios profesionales.',
    image: TOUR_IMAGES.atacama,
    guideId: '2',
    guideName: 'Matías Soto',
    guideAvatar: AVATAR_IMAGES.matias,
    guideRating: 4.8,
    location: 'San Pedro de Atacama',
    duration: '3 horas',
    price: 55000,
    currency: 'CLP',
    maxParticipants: 8,
    categories: ['astronomy', 'photography'],
    includes: ['Telescopios', 'Guía astrónomo', 'Snack y bebida caliente'],
    rating: 4.9,
    reviewCount: 203,
    featured: true,
  },
  {
    id: '3',
    title: 'Cerros de Valparaíso y Street Art',
    description: 'Recorre los coloridos cerros del puerto, sus murales y ascensores patrimoniales.',
    image: TOUR_IMAGES.valparaiso,
    guideId: '3',
    guideName: 'Francisca Vargas',
    guideAvatar: AVATAR_IMAGES.francisca,
    guideRating: 4.7,
    location: 'Valparaíso',
    duration: '3.5 horas',
    price: 28000,
    currency: 'CLP',
    maxParticipants: 12,
    categories: ['cultural', 'photography'],
    includes: ['Guía local', 'Pasaje en ascensor', 'Empanada de mariscos'],
    rating: 4.7,
    reviewCount: 95,
    featured: true,
  },
  {
    id: '4',
    title: 'Trekking Torres del Paine',
    description: 'Expedición de un día a la base de las Torres con vistas espectaculares.',
    image: TOUR_IMAGES.torres,
    guideId: '4',
    guideName: 'Sebastián Lagos',
    guideAvatar: AVATAR_IMAGES.sebastian,
    guideRating: 4.9,
    location: 'Puerto Natales',
    duration: '10 horas',
    price: 120000,
    currency: 'CLP',
    maxParticipants: 6,
    categories: ['trekking', 'nature', 'photography'],
    includes: ['Transporte', 'Entrada al parque', 'Almuerzo', 'Equipo de seguridad'],
    rating: 4.9,
    reviewCount: 312,
    featured: true,
  },
  {
    id: '5',
    title: 'Volcán Villarrica al Amanecer',
    description: 'Ascenso al cráter activo del Villarrica para ver el amanecer desde la cumbre.',
    image: TOUR_IMAGES.pucon,
    guideId: '5',
    guideName: 'Valentina Reyes',
    guideAvatar: AVATAR_IMAGES.valentina,
    guideRating: 4.6,
    location: 'Pucón',
    duration: '8 horas',
    price: 95000,
    currency: 'CLP',
    maxParticipants: 8,
    categories: ['adventure', 'trekking', 'photography'],
    includes: ['Equipo completo', 'Guía certificado', 'Transporte', 'Seguro'],
    rating: 4.8,
    reviewCount: 156,
    featured: true,
  },
  {
    id: '6',
    title: 'Ruta del Vino: Valle de Casablanca',
    description: 'Visita a las mejores viñas del valle con degustación premium y almuerzo gourmet.',
    image: TOUR_IMAGES.wine,
    guideId: '1',
    guideName: 'Carolina Muñoz',
    guideAvatar: AVATAR_IMAGES.carolina,
    guideRating: 4.9,
    location: 'Santiago',
    duration: '7 horas',
    price: 85000,
    currency: 'CLP',
    maxParticipants: 8,
    categories: ['wine', 'gastronomy'],
    includes: ['Transporte', 'Visita a 3 viñas', 'Degustaciones', 'Almuerzo'],
    rating: 4.8,
    reviewCount: 89,
    featured: false,
  },
  {
    id: '7',
    title: 'Valle del Elqui: Pisco y Estrellas',
    description: 'Tour por destilerías de pisco artesanal y observación astronómica nocturna.',
    image: TOUR_IMAGES.elqui,
    guideId: '6',
    guideName: 'Rodrigo Fuentes',
    guideAvatar: AVATAR_IMAGES.rodrigo,
    guideRating: 4.8,
    location: 'Valle del Elqui',
    duration: '6 horas',
    price: 65000,
    currency: 'CLP',
    maxParticipants: 10,
    categories: ['astronomy', 'gastronomy'],
    includes: ['Degustación de pisco', 'Observación astronómica', 'Cena típica'],
    rating: 4.7,
    reviewCount: 78,
    featured: true,
  },
  {
    id: '8',
    title: 'Cajón del Maipo: Naturaleza y Termas',
    description: 'Escapada a la montaña con trekking suave y relajación en termas naturales.',
    image: TOUR_IMAGES.cajon,
    guideId: '1',
    guideName: 'Carolina Muñoz',
    guideAvatar: AVATAR_IMAGES.carolina,
    guideRating: 4.9,
    location: 'Cajón del Maipo',
    duration: '8 horas',
    price: 75000,
    currency: 'CLP',
    maxParticipants: 8,
    categories: ['nature', 'adventure'],
    includes: ['Transporte', 'Entrada a termas', 'Guía', 'Snacks'],
    rating: 4.6,
    reviewCount: 67,
    featured: false,
  },
];

export const LANGUAGES = [
  'Español',
  'Inglés',
  'Francés',
  'Alemán',
  'Italiano',
  'Portugués',
  'Chino',
  'Japonés',
  'Mapudungun',
];

export const LOCATIONS = [
  'Santiago',
  'Valparaíso',
  'Viña del Mar',
  'San Pedro de Atacama',
  'Puerto Natales',
  'Pucón',
  'Puerto Varas',
  'La Serena',
  'Valle del Elqui',
  'Cajón del Maipo',
  'Chiloé',
];
